# Bibliotecas

In [1]:
import math
import numpy as np

## 1. Funções de Vetores

In [2]:
def soma_vet_m(v1, v2):
    res = []
    for i in range(len(v1)):
        res.append(v1[i] + v2[i])
    return res

def soma_vet_np(v1, v2):
    return np.add(v1, v2)

def sub_vet_m(v1, v2):
    res = []
    for i in range(len(v1)):
        res.append(v1[i] - v2[i])
    return res

def sub_vet_np(v1, v2):
    return np.subtract(v1, v2)

def norma_vet_m(v):
    return math.sqrt(prod_esc_m(v, v))

def norma_vet_np(v):
    return np.linalg.norm(v)

def prod_esc_m(v1, v2):
    prod = 0
    for i in range(len(v1)):
        prod += v1[i] * v2[i]
    return prod

def prod_esc_np(v1, v2):
    return np.dot(v1, v2)

def dist_euc_m(v1, v2):
    vet_sub = sub_vet_m(v1, v2)
    return norma_vet_m(vet_sub)

def dist_euc_np(v1, v2):
    return np.linalg.norm(np.subtract(v1, v2))

def mult_mat_vet_m(m, v):
    res = []
    for linha in m:
        res.append(prod_esc_m(linha, v))
    return res

def normalizar_vet_m(v):
    norma = norma_vet_m(v)
    if norma == 0:
        return v
    return [elem / norma for elem in v]

## 2. Funções de Matrizes

In [3]:
def soma_mat_m(m1, m2):
    linhas = len(m1)
    if linhas == 0:
        return []
    cols = len(m1[0])
    res = []
    for i in range(linhas):
        linha_res = []
        for j in range(cols):
            linha_res.append(m1[i][j] + m2[i][j])
        res.append(linha_res)
    return res

def soma_mat_np(m1, m2):
    return np.add(m1, m2)

def sub_mat_m(m1, m2):
    linhas = len(m1)
    if linhas == 0:
        return []
    cols = len(m1[0])
    res = []
    for i in range(linhas):
        linha_res = []
        for j in range(cols):
            linha_res.append(m1[i][j] - m2[i][j])
        res.append(linha_res)
    return res

def sub_mat_np(m1, m2):
    return np.subtract(m1, m2)

def mult_mat_m(m1, m2):
    l1 = len(m1)
    c1 = len(m1[0]) if l1 > 0 else 0
    l2 = len(m2)
    c2 = len(m2[0]) if l2 > 0 else 0
    
    m2_t = []
    for i in range(c2):
        nova_col = []
        for j in range(l2):
            nova_col.append(m2[j][i])
        m2_t.append(nova_col)
    res = []
    for l_m1 in m1:
        n_linha = []
        for c_m2 in m2_t:
            p = prod_esc_m(l_m1, c_m2) 
            n_linha.append(p)
        res.append(n_linha)
    return res

def mult_mat_np(m1, m2):
    return np.dot(m1, m2)

def det_m(m):
    a, b, c = m[0]
    d, e, f = m[1]
    g, h, i = m[2]
    d_pos = (a * e * i) + (b * f * g) + (c * d * h)
    d_neg = (c * e * g) + (b * d * i) + (a * f * h)
    return d_pos - d_neg

def det_np(m):
    return np.linalg.det(m)

def inv_m(m):
    det = det_m(m)
    
    cof = []
    c00 = (m[1][1] * m[2][2]) - (m[1][2] * m[2][1])
    c01 = -((m[1][0] * m[2][2]) - (m[1][2] * m[2][0]))
    c02 = (m[1][0] * m[2][1]) - (m[1][1] * m[2][0])
    cof.append([c00, c01, c02])
    c10 = -((m[0][1] * m[2][2]) - (m[0][2] * m[2][1]))
    c11 = (m[0][0] * m[2][2]) - (m[0][2] * m[2][0])
    c12 = -((m[0][0] * m[2][1]) - (m[0][1] * m[2][0]))
    cof.append([c10, c11, c12])
    c20 = (m[0][1] * m[1][2]) - (m[0][2] * m[1][1])
    c21 = -((m[0][0] * m[1][2]) - (m[0][2] * m[1][0]))
    c22 = (m[0][0] * m[1][1]) - (m[0][1] * m[1][0])
    cof.append([c20, c21, c22])
    adj = [
        [cof[0][0], cof[1][0], cof[2][0]],
        [cof[0][1], cof[1][1], cof[2][1]],
        [cof[0][2], cof[1][2], cof[2][2]]
    ]
    i_det = 1.0 / det 
    inv = [
        [elem * i_det for elem in linha] for linha in adj
    ]
    return inv

def inv_np(m):
    return np.linalg.inv(m)

## 3. Autovalores e Autovetores

In [ ]:
def auto_val_vet_np(m):
        return np.linalg.eig(m)

## 4. Exemplos e Resultados

In [5]:
n = int(input("Digite a dimensão (n) dos vetores: "))

v_a = []
print(f"\nDigite os {n} elementos do vetor v_a:")
for i in range(n):
    val = float(input(f"  v_a[{i}]: "))
    v_a.append(val)

v_b = []
print(f"\nDigite os {n} elementos do vetor v_b:")
for i in range(n):
    val = float(input(f"  v_b[{i}]: "))
    v_b.append(val)

np_v_a = np.array(v_a)
np_v_b = np.array(v_b)

print("\n 1. VETORES")
print(f"v_a = {v_a}, v_b = {v_b}")

print("\n1.1: Soma")
print(f"  Manual: {soma_vet_m(v_a, v_b)}")
print(f"  NumPy:  {soma_vet_np(np_v_a, np_v_b)}")

print("\n1.2: Subtração")
print(f"  Manual: {sub_vet_m(v_a, v_b)}")
print(f"  NumPy:  {sub_vet_np(np_v_a, np_v_b)}")

print(f"\n1.3: Norma (||v_a||)")
print(f"  Manual: {norma_vet_m(v_a)}")
print(f"  NumPy:  {norma_vet_np(np_v_a)}")

print("\n1.4: Produto Escalar")
print(f"  Manual: {prod_esc_m(v_a, v_b)}")
print(f"  NumPy:  {prod_esc_np(np_v_a, np_v_b)}")

print("\n1.5: Distância Euclidiana")
print(f"  Manual: {dist_euc_m(v_a, v_b)}")
print(f"  NumPy:  {dist_euc_np(np_v_a, np_v_b)}")



Digite os 3 elementos do vetor v_a:

Digite os 3 elementos do vetor v_b:

 1. VETORES
v_a = [3.0, 2.0, 2.0], v_b = [2.0, 2.0, 2.0]

1.1: Soma
  Manual: [5.0, 4.0, 4.0]
  NumPy:  [5. 4. 4.]

1.2: Subtração
  Manual: [1.0, 0.0, 0.0]
  NumPy:  [1. 0. 0.]

1.3: Norma (||v_a||)
  Manual: 4.123105625617661
  NumPy:  4.123105625617661

1.4: Produto Escalar
  Manual: 14.0
  NumPy:  14.0

1.5: Distância Euclidiana
  Manual: 1.0
  NumPy:  1.0


In [6]:
m_a = [[1, 2, 3], 
       [4, 5, 6], 
       [7, 8, 10]] 
       
m_b = [[1, 2, 1], 
       [0, 1, 3], 
       [2, 0, 1]] 
       
np_m_a = np.array(m_a)
np_m_b = np.array(m_b)


print("\n\n 2. MATRIZES")
print(f"m_a =\n{np_m_a}")
print(f"\nm_b =\n{np_m_b}")

print("\n2.1: Soma (m_a + m_b)")
print(f"  Manual:\n{np.array(soma_mat_m(m_a, m_b))}")
print(f"  NumPy:\n{soma_mat_np(np_m_a, np_m_b)}")

print("\n2.2: Subtração (m_a - m_b)")
print(f"  Manual:\n{np.array(sub_mat_m(m_a, m_b))}")
print(f"  NumPy:\n{sub_mat_np(np_m_a, np_m_b)}")

print("\n2.3: Multiplicação (m_a * m_b)")
print(f"  Manual:\n{np.array(mult_mat_m(m_a, m_b))}")
print(f"  NumPy:\n{mult_mat_np(np_m_a, np_m_b)}")

print("\n2.4: Determinante")
print(f"  det(m_a) Manual: {det_m(m_a)}")
print(f"  det(m_a) NumPy:  {det_np(np_m_a) }")
print(f"  det(m_b) Manual: {det_m(m_b)}")
print(f"  det(m_b) NumPy:  {det_np(np_m_b)}")

print("\n2.5: Inversa")
print(f"  inv(m_a) Manual:\n{np.array(inv_m(m_a))}")
print(f"  inv(m_a) NumPy:\n{inv_np(np_m_a)}")
print(f"  inv(m_t) Manual:\n{np.array(inv_m(m_b))}")
print(f"  inv(m_b) NumPy:\n{inv_np(np_m_b)}")



 2. MATRIZES
m_a =
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

m_b =
[[1 2 1]
 [0 1 3]
 [2 0 1]]

2.1: Soma (m_a + m_b)
  Manual:
[[ 2  4  4]
 [ 4  6  9]
 [ 9  8 11]]
  NumPy:
[[ 2  4  4]
 [ 4  6  9]
 [ 9  8 11]]

2.2: Subtração (m_a - m_b)
  Manual:
[[0 0 2]
 [4 4 3]
 [5 8 9]]
  NumPy:
[[0 0 2]
 [4 4 3]
 [5 8 9]]

2.3: Multiplicação (m_a * m_b)
  Manual:
[[ 7  4 10]
 [16 13 25]
 [27 22 41]]
  NumPy:
[[ 7  4 10]
 [16 13 25]
 [27 22 41]]

2.4: Determinante
  det(m_a) Manual: -3
  det(m_a) NumPy:  -2.9999999999999996
  det(m_b) Manual: 11
  det(m_b) NumPy:  11.000000000000002

2.5: Inversa
  inv(m_a) Manual:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
  inv(m_a) NumPy:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
  inv(m_t) Manual:
[[ 0.09090909 -0.18181818  0.45454545]
 [ 0.54545455 -0.09090909 -0.27272727]
 [-0.18181818  0.36363636  0.09090909]]

In [ ]:
print("\n\n 3. AUTOVALORES E AUTOVETORES")

print(f"\nCálculo para m_a:\n{np_m_a}")
auto_val_a, auto_vet_a = auto_val_vet_np(np_m_a)
print(f"\n  Autovalores:\n  {auto_val_a}")
print(f"\n  Autovetores (colunas):\n{auto_vet_a}")

print(f"\nCálculo para m_b:\n{np_m_b}")
auto_val_b, auto_vet_b = auto_val_vet_np(np_m_b)
print(f"\n  Autovalores:\n  {auto_val_b}")
print(f"\n  Autovetores (colunas):\n{auto_vet_b}")



 3. AUTOVALORES E AUTOVETORES

Cálculo para m_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

  Autovalores:
  [16.70749332 -0.90574018  0.19824686]

  Autovetores (colunas):
[[-0.22351336 -0.86584578  0.27829649]
 [-0.50394563  0.0856512  -0.8318468 ]
 [-0.83431444  0.4929249   0.48018951]]

  Manual (Autovalor Dominante): 16.70749331612475
  Manual (Autovetor Dominante): [0.22351335772785175, 0.5039456275263904, 0.8343144391740167]

  Manual (Autovalor Mínimo): 0.19824686339701011
  Manual (Autovetor Mínimo): [-0.2782964859805726, 0.8318468022052949, -0.48018950795669196]

Cálculo para m_b:
[[1 2 1]
 [0 1 3]
 [2 0 1]]

  Autovalores:
  [ 3.5792478+0.j         -0.2896239+1.72898508j -0.2896239-1.72898508j]

  Autovetores (colunas):
[[ 0.64352612+0.j         -0.15187682-0.51067814j -0.15187682+0.51067814j]
 [ 0.5804052 +0.j          0.68709091+0.j          0.68709091-0.j        ]
 [ 0.49900294+0.j         -0.29536296+0.39598998j -0.29536296-0.39598998j]]

  Manual (Autovalor Dominante): 3.5