# Bibliotecas

In [6]:
import math
import numpy as np

## 1. Funções de Vetores

In [7]:
def soma_vetor_manual(v1, v2):
    if len(v1) != len(v2):
        raise ValueError("Vetores devem ter o mesmo tamanho para adição.")
    return [a + b for a, b in zip(v1, v2)]

def soma_vetor_numpy(v1, v2):
    return np.add(v1, v2)

def subtracao_vetor_manual(v1, v2):
    if len(v1) != len(v2):
        raise ValueError("Vetores devem ter o mesmo tamanho para subtração.")
    return [a - b for a, b in zip(v1, v2)]

def subtracao_vetor_numpy(v1, v2):
    return np.subtract(v1, v2)

def norma_vetor_manual(v):
    return math.sqrt(produto_escalar_manual(v, v))

def norma_vetor_numpy(v):
    return np.linalg.norm(v)

def produto_escalar_manual(v1, v2):
    if len(v1) != len(v2):
        raise ValueError("Vetores devem ter o mesmo tamanho para produto escalar.")
    return sum(a * b for a, b in zip(v1, v2))

def produto_escalar_numpy(v1, v2):
    return np.dot(v1, v2)

def distancia_euclidiana_manual(v1, v2):
    if len(v1) != len(v2):
        raise ValueError("Vetores devem ter o mesmo tamanho para distância euclidiana.")
    vetor_subtraido = subtracao_vetor_manual(v1, v2)
    return norma_vetor_manual(vetor_subtraido)

def distancia_euclidiana_numpy(v1, v2):
    return np.linalg.norm(np.subtract(v1, v2))

## 2. Funções de Matrizes

In [8]:
def soma_matriz_manual(m1, m2):
    if len(m1) != len(m2) or len(m1[0]) != len(m2[0]):
        raise ValueError("Matrizes devem ter as mesmas dimensões para adição.")
    
    return [[c1 + c2 for c1, c2 in zip(linha1, linha2)] for linha1, linha2 in zip(m1, m2)]

def soma_matriz_numpy(m1, m2):
    return np.add(m1, m2)

def subtracao_matriz_manual(m1, m2):
    if len(m1) != len(m2) or len(m1[0]) != len(m2[0]):
        raise ValueError("Matrizes devem ter as mesmas dimensões para subtração.")
    
    return [[c1 - c2 for c1, c2 in zip(linha1, linha2)] for linha1, linha2 in zip(m1, m2)]

def subtracao_matriz_numpy(m1, m2):
    return np.subtract(m1, m2)

def multiplicacao_matriz_manual(m1, m2):
    linhas_m1 = len(m1)
    cols_m1 = len(m1[0]) if linhas_m1 > 0 else 0
    linhas_m2 = len(m2)
    cols_m2 = len(m2[0]) if linhas_m2 > 0 else 0

    if cols_m1 != linhas_m2:
        raise ValueError(f"Número de colunas de m1 ({cols_m1}) deve ser igual ao número de linhas de m2 ({linhas_m2}).")

    m2_transposta = [[m2[j][i] for j in range(linhas_m2)] for i in range(cols_m2)]
    
    resultado = []
    for linha_m1 in m1:
        nova_linha = []
        for col_m2 in m2_transposta:
            produto = produto_escalar_manual(linha_m1, col_m2)
            nova_linha.append(produto)
        resultado.append(nova_linha)
        
    return resultado

def multiplicacao_matriz_numpy(m1, m2):
    return np.dot(m1, m2)

def determinante_3x3_manual(m):
    if len(m) != 3 or len(m[0]) != 3:
        raise ValueError("Implementação manual do determinante é apenas para 3x3.")
        
    a, b, c = m[0]
    d, e, f = m[1]
    g, h, i = m[2]
    
    det_pos = (a * e * i) + (b * f * g) + (c * d * h)
    det_neg = (c * e * g) + (b * d * i) + (a * f * h)
    
    return det_pos - det_neg

def determinante_numpy(m):
    return np.linalg.det(m)

def inversa_3x3_manual(m):
    if len(m) != 3 or len(m[0]) != 3:
        raise ValueError("Implementação manual da inversa é apenas para 3x3.")

    det = determinante_3x3_manual(m)
    if det == 0:
        raise ValueError("Matriz é singular (determinante é zero) e não pode ser invertida.")

    cofatores = []
    c00 = (m[1][1] * m[2][2]) - (m[1][2] * m[2][1])
    c01 = -((m[1][0] * m[2][2]) - (m[1][2] * m[2][0]))
    c02 = (m[1][0] * m[2][1]) - (m[1][1] * m[2][0])
    cofatores.append([c00, c01, c02])
    
    c10 = -((m[0][1] * m[2][2]) - (m[0][2] * m[2][1]))
    c11 = (m[0][0] * m[2][2]) - (m[0][2] * m[2][0])
    c12 = -((m[0][0] * m[2][1]) - (m[0][1] * m[2][0]))
    cofatores.append([c10, c11, c12])

    c20 = (m[0][1] * m[1][2]) - (m[0][2] * m[1][1])
    c21 = -((m[0][0] * m[1][2]) - (m[0][2] * m[1][0]))
    c22 = (m[0][0] * m[1][1]) - (m[0][1] * m[1][0])
    cofatores.append([c20, c21, c22])

    adjunta = [
        [cofatores[0][0], cofatores[1][0], cofatores[2][0]],
        [cofatores[0][1], cofatores[1][1], cofatores[2][1]],
        [cofatores[0][2], cofatores[1][2], cofatores[2][2]]
    ]
    
    inv_det = 1.0 / det
    inversa = [
        [elem * inv_det for elem in linha] for linha in adjunta
    ]
    
    return inversa

def inversa_numpy(m):
    return np.linalg.inv(m)

## 3. Autovalores e Autovetores

In [9]:
def autovalores_autovetores_numpy(m):
    try:
        return np.linalg.eig(m)
    except np.linalg.LinAlgError as e:
        raise ValueError(f"Erro ao calcular autovalores/autovetores: {str(e)}")

## 4. Exemplos e Resultados

In [ ]:
vetor_a = [1, 2, 3]
vetor_b = [4, 5, 6]

np_vetor_a = np.array(vetor_a)
np_vetor_b = np.array(vetor_b)

print("\n 1. VETORES")
print(f"vetor_a = {vetor_a}, vetor_b = {vetor_b}")

print("\n1.1: Soma")
print(f"  Manual: {soma_vetor_manual(vetor_a, vetor_b)}")
print(f"  NumPy:  {soma_vetor_numpy(np_vetor_a, np_vetor_b)}")

print("\n1.2: Subtração")
print(f"  Manual: {subtracao_vetor_manual(vetor_a, vetor_b)}")
print(f"  NumPy:  {subtracao_vetor_numpy(np_vetor_a, np_vetor_b)}")

print(f"\n1.3: Norma (||vetor_a||)")
print(f"  Manual: {norma_vetor_manual(vetor_a):.4f}")
print(f"  NumPy:  {norma_vetor_numpy(np_vetor_a):.4f}")

print("\n1.4: Produto Escalar")
print(f"  Manual: {produto_escalar_manual(vetor_a, vetor_b)}")
print(f"  NumPy:  {produto_escalar_numpy(np_vetor_a, np_vetor_b)}")

print("\n1.5: Distância Euclidiana")
print(f"  Manual: {distancia_euclidiana_manual(vetor_a, vetor_b):.4f}")
print(f"  NumPy:  {distancia_euclidiana_numpy(np_vetor_a, np_vetor_b):.4f}")


--- 1. VETORES ---
vetor_a = [1, 2, 3], vetor_b = [4, 5, 6]

1.1: Soma
  Manual: [5, 7, 9]
  NumPy:  [5 7 9]

1.2: Subtração
  Manual: [-3, -3, -3]
  NumPy:  [-3 -3 -3]

1.3: Norma (||vetor_a||)
  Manual: 3.7417
  NumPy:  3.7417

1.4: Produto Escalar
  Manual: 32
  NumPy:  32

1.5: Distância Euclidiana
  Manual: 5.1962
  NumPy:  5.1962


In [ ]:
matriz_a = [[1, 2, 3], 
            [4, 5, 6], 
            [7, 8, 9]]
       
matriz_b = [[9, 8, 7], 
            [6, 5, 4], 
            [3, 2, 1]]

matriz_c = [[1, 2, 1], 
            [0, 1, 3], 
            [2, 0, 1]]
       
np_matriz_a = np.array(matriz_a)
np_matriz_b = np.array(matriz_b)
np_matriz_c = np.array(matriz_c)

print("\n\n 2. MATRIZES")
print(f"matriz_a =\n{np_matriz_a}")
print(f"\nmatriz_b =\n{np_matriz_b}")
print(f"\nmatriz_c =\n{np_matriz_c}")

print("\n2.1: Soma (matriz_a + matriz_b)")
print(f"  Manual:\n{np.array(soma_matriz_manual(matriz_a, matriz_b))}")
print(f"  NumPy:\n{soma_matriz_numpy(np_matriz_a, np_matriz_b)}")

print("\n2.2: Subtração (matriz_a - matriz_b)")
print(f"  Manual:\n{np.array(subtracao_matriz_manual(matriz_a, matriz_b))}")
print(f"  NumPy:\n{subtracao_matriz_numpy(np_matriz_a, np_matriz_b)}")

print("\n2.3: Multiplicação (matriz_a * matriz_b)")
print(f"  Manual:\n{np.array(multiplicacao_matriz_manual(matriz_a, matriz_b))}")
print(f"  NumPy:\n{multiplicacao_matriz_numpy(np_matriz_a, np_matriz_b)}")

print("\n2.4: Determinante (det(matriz_c))")
print(f"  Manual (3x3): {determinante_3x3_manual(matriz_c):.4f}")
print(f"  NumPy:        {determinante_numpy(np_matriz_c):.4f}")

print("\n2.5: Inversa (inv(matriz_c))")
print(f"  Manual (3x3):\n{np.array(inversa_3x3_manual(matriz_c))}")
print(f"  NumPy:\n{inversa_numpy(np_matriz_c)}")



--- 2. MATRIZES ---
matriz_a =
[[1 2 3]
 [4 5 6]
 [7 8 9]]

matriz_b =
[[9 8 7]
 [6 5 4]
 [3 2 1]]

matriz_c =
[[1 2 1]
 [0 1 3]
 [2 0 1]]

2.1: Soma (matriz_a + matriz_b)
  Manual:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
  NumPy:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

2.2: Subtração (matriz_a - matriz_b)
  Manual:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
  NumPy:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

2.3: Multiplicação (matriz_a * matriz_b)
  Manual:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
  NumPy:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

2.4: Determinante (det(matriz_c))
  Manual (3x3): 11.0000
  NumPy:        11.0000

2.5: Inversa (inv(matriz_c))
  Manual (3x3):
[[ 0.09090909 -0.18181818  0.45454545]
 [ 0.54545455 -0.09090909 -0.27272727]
 [-0.18181818  0.36363636  0.09090909]]
  NumPy:
[[ 0.09090909 -0.18181818  0.45454545]
 [ 0.54545455 -0.09090909 -0.27272727]
 [-0.18181818  0.36363636  0.09090909]]


In [ ]:
print("\n\n 3. AUTOVALORES E AUTOVETORES")

print(f"\nCálculo para matriz_c:\n{np_matriz_c}")
autovalores, autovetores = autovalores_autovetores_numpy(np_matriz_c)
print(f"\n  Autovalores:\n  {autovalores}")
print(f"\n  Autovetores (colunas):\n{autovetores}")



--- 3. AUTOVALORES E AUTOVETORES ---

Cálculo para matriz_c:
[[1 2 1]
 [0 1 3]
 [2 0 1]]

  Autovalores:
  [ 3.5792478+0.j         -0.2896239+1.72898508j -0.2896239-1.72898508j]

  Autovetores (colunas):
[[ 0.64352612+0.j         -0.15187682-0.51067814j -0.15187682+0.51067814j]
 [ 0.5804052 +0.j          0.68709091+0.j          0.68709091-0.j        ]
 [ 0.49900294+0.j         -0.29536296+0.39598998j -0.29536296-0.39598998j]]
